### ISSUE TITLE
Ubuntu 20.04 error, How to fix this issue?

### ISSUE THREAD

**Issue by x1337cn** [mpudliszewski/samp_monitor_bot#1]
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'node:events'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/root/samp_monitor_bot/node_modules/discord.js/src/client/BaseClient.js:3:22)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)

**Comment by mpudliszewski** [comment]
Try to update node to at least 16.9.0
To check current version use `node -v` command
